
CREATE TABLE users (
  user_id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  phone VARCHAR(20),
  password TEXT NOT NULL,
  is_varified BOOLEAN DEFAULT FALSE,
  varification_token TEXT NULL,
  recover_token TEXT NULL,
  recover_token_expires TIMESTAMP DEFAULT NULL,
  role TEXT DEFAULT 'user'
    CHECK (role IN ('admin','manager','sales','user')),
  is_active BOOLEAN DEFAULT TRUE,
  is_banned BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

-- =====================================================
-- CUSTOMERS
-- =====================================================
CREATE TABLE customers (
  customer_id SERIAL PRIMARY KEY,
  name VARCHAR(100),
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(100),
  address TEXT,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE categories (
  category_id SERIAL PRIMARY KEY,
  parent_id INT REFERENCES categories(category_id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) NOT NULL,
image TEXT NOT NULL,
image_id TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE brands (
  brand_id SERIAL PRIMARY KEY,
image TEXT NOT NULL,
image_id TEXT NOT NULL,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE products (
    product_id SERIAL PRIMARY KEY,

    category_id INT REFERENCES categories(category_id),
    brand_id INT REFERENCES brands(brand_id),

    name VARCHAR(150) NOT NULL,
    slug VARCHAR(150) UNIQUE,
    description TEXT,

    is_active BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE product_variants (
    variant_id SERIAL PRIMARY KEY,
    product_id INT NOT NULL
        REFERENCES products(product_id)
        ON DELETE CASCADE,
    variant_name VARCHAR(150) DEFAULT 'Default',
    barcode VARCHAR(100) UNIQUE,
    purchase_price NUMERIC(10,2) NOT NULL,

    sale_price NUMERIC(10,2) NOT NULL,
    discount_price NUMERIC(10,2) DEFAULT 0,
    wholesale_price NUMERIC(10,2),
    dealer_price NUMERIC(10,2),
    retail_price NUMERIC(10,2),

    stock INT DEFAULT 0,

    image TEXT,
    image_id VARCHAR(255),

    weight NUMERIC(10,2),
    unit VARCHAR(30),

    is_active BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now()
);



CREATE TABLE suppliers (
  supplier_id SERIAL PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  company_name VARCHAR(200),
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(150),
  address TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);



CREATE TABLE purchases (
  purchase_id SERIAL PRIMARY KEY,
  supplier_id INT REFERENCES suppliers(supplier_id),
  supplier_name VARCHAR(200),
  supplier_phone VARCHAR(20),
  invoice_no VARCHAR(100),
  subtotal_amount NUMERIC(10,2) DEFAULT 0,
  extra_discount NUMERIC(10,2) DEFAULT 0,
  total_amount NUMERIC(10,2) DEFAULT 0,
  payment_method VARCHAR(50),
  transaction_id VARCHAR(100),
  note TEXT,
  created_at TIMESTAMP DEFAULT now()
);


CREATE TABLE purchase_items (
  id SERIAL PRIMARY KEY,
  purchase_id INT REFERENCES purchases(purchase_id) ON DELETE CASCADE,
  product_id INT REFERENCES products(product_id),
  variant_id  INT REFERENCES product_variants(variant_id) ON DELETE SET NULL,
  quantity INT NOT NULL,
  purchase_price NUMERIC(10,2) NOT NULL
);


CREATE TABLE purchase_payments (
  payment_id SERIAL PRIMARY KEY,
  purchase_id INT REFERENCES purchases(purchase_id),
  payment_method VARCHAR(50),
  amount_paid NUMERIC(10,2),
  transaction_id VARCHAR(100),
  payment_date TIMESTAMP DEFAULT now()
);


CREATE TABLE public.orders (
    order_id            SERIAL PRIMARY KEY,
    customer_id         INTEGER REFERENCES public.customers(customer_id),
    phone               VARCHAR(20) NOT NULL,
    shipping_address    TEXT NOT NULL,
    shipping_city       VARCHAR(100),
    shipping_area       VARCHAR(100),
    courier_name        VARCHAR(100),
    courier_tracking_id VARCHAR(100),
    status              VARCHAR(30) DEFAULT 'pending'
                        CHECK (status IN (
                            'pending', 'confirmed', 'processing', 'shipped', 
                            'out_for_delivery', 'delivered', 'cancelled', 
                            'returned', 'failed'
                        )),
    subtotal_amount       NUMERIC(10, 2) NOT NULL,       -- Sum of products
    total_discount_amount NUMERIC(10, 2) DEFAULT 0,      -- Coupons/Discounts
    delivery_charge       NUMERIC(10, 2) DEFAULT 0,      -- Shipping cost
    total_amount          NUMERIC(10, 2) NOT NULL,       -- (Subtotal + Delivery) - Discount
    due_amount            NUMERIC(10, 2) DEFAULT 0,      -- Balance to be paid
    payment_type        VARCHAR(20) DEFAULT 'cod'        -- 'cod' or 'prepaid'
                    CHECK (payment_type IN ('cod', 'prepaid')),
    note                TEXT,
    created_at          TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at          TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);


CREATE TABLE order_items (
  order_item_id SERIAL PRIMARY KEY,
  order_id   INT REFERENCES orders(order_id) ON DELETE CASCADE,
  product_id INT REFERENCES products(product_id),
  variant_id INT REFERENCES product_variants(variant_id) ON DELETE SET NULL,  -- NULL for non-variant items
  quantity INT NOT NULL,
  price NUMERIC(10,2) NOT NULL
);


CREATE TABLE public.payments (
    payment_id       SERIAL PRIMARY KEY,
    order_id         INTEGER NOT NULL REFERENCES public.orders(order_id) ON DELETE CASCADE,
    payment_method   VARCHAR(50),
    transaction_id   VARCHAR(100), 
    amount           NUMERIC(10, 2) NOT NULL,
    amount_received  NUMERIC(10, 2) DEFAULT 0,
    change_amount    NUMERIC(10, 2) DEFAULT 0,
    payment_status   VARCHAR(30) DEFAULT 'pending'
                     CHECK (payment_status IN (
                        'pending',  
                        'failed', 
                        'refunded', 
                        'partial', 
                        'completed'
                     )),
    paid_at          TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    note             TEXT
);

CREATE INDEX idx_payments_order_id ON public.payments(order_id);
CREATE INDEX idx_payments_payment_method ON public.payments(payment_method);

;

CREATE TABLE inventory_logs (
  log_id SERIAL PRIMARY KEY,
  product_id INT REFERENCES products(product_id),
  type TEXT CHECK (type IN ('purchase','sale','adjustment','return')),
  quantity INT NOT NULL,
  reference_id INT,
  note TEXT,
  created_at TIMESTAMP DEFAULT now()
);


CREATE TABLE refunds (
  refund_id SERIAL PRIMARY KEY,
  order_id INT REFERENCES orders(order_id),
  amount NUMERIC(10,2),
  reason TEXT,
  status TEXT DEFAULT 'pending'
    CHECK (status IN ('pending','approved','rejected')),
  created_at TIMESTAMP DEFAULT now()
);





CREATE TABLE issues (
  issue_id SERIAL PRIMARY KEY,
  sender_id INT REFERENCES users(user_id) ON DELETE CASCADE,
  receiver_id INT REFERENCES users(user_id) ON DELETE CASCADE,
  title VARCHAR(200) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT now()
);

CREATE OR REPLACE VIEW issues_view AS
SELECT 
  i.issue_id,
  i.sender_id,
  s.name AS sender_name,
  s.email AS sender_email,
  s.role AS sender_role,
  i.receiver_id,
  r.name AS receiver_name,
  r.email AS receiver_email,
  r.role AS receiver_role,
  i.title,
  i.message,
  i.created_at
FROM issues i
LEFT JOIN users s ON i.sender_id = s.user_id
LEFT JOIN users r ON i.receiver_id = r.user_id;

CREATE TABLE websites (
  website_id SERIAL PRIMARY KEY,
  logo TEXT,
  logo_id TEXT,
  theme_color TEXT,

  hero_title TEXT,
  hero_subtitle TEXT,

  address TEXT,
  sociallink TEXT,
  email TEXT,
  phone TEXT,

  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);
